name: For every push

<<<<<<< HEAD
name: DNI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
=======
on: [push]
>>>>>>> c3f476b5315f77767558213555680c7404fb763a

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v1
        env:
          TEST_NAME: CalculadoraTest
        with:
          configuration: test/phpunit.xml
          args: --coverage-text
  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/calculadora:${{ github.sha }} .
          docker build -t ${{ secrets.DOCKER_USER }}/calculadora:latest .
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/calculadora:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/calculadora:latest 